pipeline {
    agent {
        label 'docker-azcli-kubectl-slave'
    }
    stages {
        stage('Build') {
            steps {
                sh 'echo Hello World'
                sh 'docker -v'
//                 sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
